### ISSUE TITLE
一部のクエストが達成されない

### ISSUE THREAD

**Issue by RunqRun** [TEAMNekozouneko/TheMining#3]
報告されたのは下記のクエストです。
・ジャンプブーストを3レベルに上げる
・ピッケルを3回アップグレードする
・第四マップに30回行く

もしも早く修正ができる方がいたら対応お願いします。

┃引用
https://discord.com/channels/896668963709255680/1203617187131162694

**Comment by onigiri3425** [comment]
ジャンプブースト・第四マップのクエストについては修正しました。ピッケルのアップグレードに関しては存在しておりませんでしたので新規作成かと思いましたが正常動作を確認しました。

**Comment by RunqRun** [comment]
対応ありがとうございます。
この件は修正済みとして進めていきます
