### ISSUE TITLE
クエスト#44 「第4MAPに30回行く」が一生完了しない

### ISSUE THREAD

**Issue by Taitaitatata** [TEAMNekozouneko/TheMining#4]
該当のクエストで30回以上行っても私の場合`40/<none>`となっており40回以上いっても一生完了できない
![image](https://github.com/TeamNekozouneko/TheMining/assets/70869837/146237e5-7637-4c61-a74c-52951abb526b)

**Comment by onigiri3425** [comment]
更新しました

**Comment by Taitaitatata** [comment]
確認しました
![image](https://github.com/TeamNekozouneko/TheMining/assets/70869837/076e06a0-4730-4514-8211-4879b8da3232)

**Comment by Taitaitatata** [comment]
この問題は閉じますね
